name: Deploy to Cloud Run from GitHub Packages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: 

env:
  PROJECT_ID: superb-tendril-454116-i5 # Replace with your Google Cloud Project ID
  REGION: us-central1 # Replace with your desired Google Cloud region
  SERVICE_NAME: demo # Replace with your Cloud Run service name
  # Define the full image URL from GitHub Packages
  # Format: ghcr.io/<OWNER>/<REPOSITORY_NAME>/<IMAGE_NAME>:<TAG>
  # Using GITHUB_REPOSITORY for owner/repo and GITHUB_SHA for a unique tag
  IMAGE_URL: ghcr.io/${{ github.repository }}/${{ github.repository }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to pull from GitHub Packages
      id-token: write # Required for Google Cloud authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # This secret should contain the JSON key for your GCP Service Account
          # with Cloud Run Admin and Service Account User roles.
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # GITHUB_TOKEN is a special token provided by GitHub Actions for authentication
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE_URL }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated # Remove this flag if you want to require authentication
          echo "Cloud Run service deployed at: $(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format 'value(status.url)')"
